import React, { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, StyleSheet, Text, View } from 'react-native';
import { Link, router } from 'expo-router';
import { Button } from '@/components/Button';
import { Input } from '@/components/Input';
import { Screen } from '@/components/Screen';
import { register } from '@/features/auth/authService';
import { colors } from '@/theme/colors';

export default function CadastroScreen() {
  const [nome, setNome] = useState(''); const [sobrenome, setSobrenome] = useState(''); const [email, setEmail] = useState(''); const [telefone, setTelefone] = useState(''); const [senha, setSenha] = useState(''); const [nascimento, setNascimento] = useState(''); const [cpf, setCpf] = useState(''); const [estado, setEstado] = useState('PE'); const [cidade, setCidade] = useState(''); const [aceite, setAceite] = useState(false); const [loading, setLoading] = useState(false);
  async function onRegister() { if (!aceite) return Alert.alert('Aceite obrigatório', 'Marque a opção de aceite dos documentos legais.'); if (nascimento.length !== 10) return Alert.alert('Nascimento', 'Use o formato DD/MM/AAAA.'); setLoading(true); try { const cidadeValue = cidade.trim();
  await register({nome: nome.trim(),sobrenome: sobrenome.trim(),email: email.trim().toLowerCase(),telefone,senha,data_nascimento: nascimento,cpf,estado: estado.toUpperCase(),...(cidadeValue ? { cidade: cidadeValue } : {}),aceita_termos: true,}); Alert.alert('Cadastro realizado', 'Sua conta foi criada. Agora entre no MOVI.', [{ text: 'Entrar', onPress: () => router.replace('/(public)/login') }]); } catch (error) { Alert.alert('Não foi possível cadastrar', error instanceof Error ? error.message : 'Confira os dados.'); } finally { setLoading(false); } }
  return <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><Screen title="Criar conta" subtitle="Vamos preparar seu perfil de passageiro."><View style={styles.form}><Input label="Nome" value={nome} onChangeText={setNome} /><Input label="Sobrenome" value={sobrenome} onChangeText={setSobrenome} /><Input label="Email" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" /><Input label="Telefone" value={telefone} onChangeText={setTelefone} keyboardType="phone-pad" /><Input label="CPF" value={cpf} onChangeText={setCpf} keyboardType="numeric" /><Input label="Nascimento (DD/MM/AAAA)" value={nascimento} onChangeText={setNascimento} keyboardType="numeric" maxLength={10} /><View style={styles.row}><View style={{ flex: 1 }}><Input label="Estado" value={estado} onChangeText={setEstado} maxLength={2} autoCapitalize="characters" /></View><View style={{ flex: 2 }}><Input label="Cidade" value={cidade} onChangeText={setCidade} /></View></View><Input label="Senha" value={senha} onChangeText={setSenha} secureTextEntry /><View style={styles.legal}><Link href="/(public)/legal/passageiro" style={styles.legalLink}>Ler Termos de Uso, Privacidade e Segurança</Link><Text accessibilityRole="checkbox" aria-checked={aceite} style={styles.accept} onPress={() => setAceite((v) => !v)}>{aceite ? '☑' : '☐'} Eu aceito os documentos legais vigentes do MOVI.</Text></View><Button title="Criar minha conta" onPress={() => void onRegister()} loading={loading} /><Link href="/(public)/login" style={styles.back}>Já tenho conta</Link></View></Screen></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ form: { gap: 14 }, row: { flexDirection: 'row', gap: 10 }, legal: { gap: 10, padding: 10 }, legalLink: { color: colors.text, textDecorationLine: 'underline', fontWeight: '700' }, accept: { color: colors.text, lineHeight: 21 }, back: { textAlign: 'center', fontWeight: '800', color: colors.text, padding: 8 } });
